// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceInvoiceImporter.Infrastructure.Data;

#nullable disable

namespace ServiceInvoiceImporter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929120616_ExtractXMLData")]
    partial class ExtractXMLData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceInvoiceImporter.Core.Domains.Invoices.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("CNPJPrestador")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CNPJTomador")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoServico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Numero");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("IDX_NotaFiscal_Numero");

                    b.ToTable("NotasFiscais", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
